[package]
name = "alloy"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst" }
alacritty = { path = "alacritty/alacritty" }
# alacritty = { git = "https://github.com/j4qfrost/alacritty" }

[profile.dev]
debug = 0

[features]
empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]

default = ["vulkan"]

[patch.crates-io]
servo-freetype-sys = { path = "alacritty/servo-freetype-proxy" }